import {DropdownItem} from './types';

export const categories: DropdownItem[] = [
  {label: 'Food', value: 'Food'},
  {label: 'Travel', value: 'Travel'},
  {label: 'Shopping', value: 'Shopping'},
  {label: 'Health', value: 'Health'},
  {label: 'Education', value: 'Education'},
  {label: 'Entertainment', value: 'Entertainment'},
  {label: 'Fitness', value: 'Fitness'},
  {label: 'Technology', value: 'Technology'},
  {label: 'Finance', value: 'Finance'},
  {label: 'Work', value: 'Work'},
  {label: 'Home', value: 'Home'},
  {label: 'Transport', value: 'Transport'},
  {label: 'Groceries', value: 'Groceries'},
  {label: 'Pets', value: 'Pets'},
  {label: 'Books', value: 'Books'},
  {label: 'Gifts', value: 'Gifts'},
  {label: 'Hobbies', value: 'Hobbies'},
  {label: 'Beauty', value: 'Beauty'},
  {label: 'Clothing', value: 'Clothing'},
  {label: 'Events', value: 'Events'},
  {label: 'Milk & Dairy', value: 'Milk & Dairy'},
  {label: 'Vegetables', value: 'Vegetables'},
  {label: 'Fruits', value: 'Fruits'},
  {label: 'Mobile Recharge', value: 'Mobile Recharge'},
  {label: 'Electricity Bill', value: 'Electricity Bill'},
  {label: 'Water Bill', value: 'Water Bill'},
  {label: 'Gas Cylinder', value: 'Gas Cylinder'},
  {label: 'Internet Bill', value: 'Internet Bill'},
  {label: 'House Rent', value: 'House Rent'},
  {label: 'Maid Salary', value: 'Maid Salary'},
  {label: 'Driver Salary', value: 'Driver Salary'},
  {label: 'Parking', value: 'Parking'},
  {label: 'Laundry', value: 'Laundry'},
  {label: 'Tea & Snacks', value: 'Tea & Snacks'},
  {label: 'Breakfast', value: 'Breakfast'},
  {label: 'Lunch', value: 'Lunch'},
  {label: 'Dinner', value: 'Dinner'},
  {label: 'ATM Withdrawal', value: 'ATM Withdrawal'},
  {label: 'Credit Card Bill', value: 'Credit Card Bill'},
  {label: 'Insurance', value: 'Insurance'},
  {label: 'EMI Payment', value: 'EMI Payment'},
  {label: 'Investment', value: 'Investment'},
  {label: 'Temple Donation', value: 'Temple Donation'},
  {label: 'Puja Items', value: 'Puja Items'},
  {label: 'Online Subscriptions', value: 'Online Subscriptions'},
  {label: 'OTT Platforms', value: 'OTT Platforms'},
  {label: 'Medicine', value: 'Medicine'},
  {label: 'Hospital', value: 'Hospital'},
  {label: 'Tuition Fees', value: 'Tuition Fees'},
  {label: 'Stationery', value: 'Stationery'},
  {label: 'Baby Care', value: 'Baby Care'},
  {label: 'Elder Care', value: 'Elder Care'},
  {label: 'Wedding', value: 'Wedding'},
  {label: 'Festival Shopping', value: 'Festival Shopping'},
  {label: 'Courier/Parcel', value: 'Courier/Parcel'},
  {label: 'Bike Fuel', value: 'Bike Fuel'},
  {label: 'Car Fuel', value: 'Car Fuel'},
  {label: 'Vehicle Maintenance', value: 'Vehicle Maintenance'},
];

export const EarningSource: DropdownItem[] = [
  {label: 'Salary', value: 'Salary'},
  {label: 'Freelancing', value: 'Freelancing'},
  {label: 'Investments', value: 'Investments'},
  {label: 'Rental Income', value: 'Rental Income'},
  {label: 'Dividends', value: 'Dividends'},
  {label: 'Interest', value: 'Interest'},
  {label: 'Business', value: 'Business'},
  {label: 'Bonus', value: 'Bonus'},
  {label: 'Consulting', value: 'Consulting'},
  {label: 'Royalties', value: 'Royalties'},
  {label: 'Grants', value: 'Grants'},
  {label: 'Pension', value: 'Pension'},
  {label: 'Social Security', value: 'Social Security'},
  {label: 'Affiliate Income', value: 'Affiliate Income'},
  {label: 'Online Sales', value: 'Online Sales'},
  {label: 'Part-time Job', value: 'Part-time Job'},
  {label: 'Crowdfunding', value: 'Crowdfunding'},
  {label: 'Scholarships', value: 'Scholarships'},
  {label: 'Cashback', value: 'Cashback'},
  {label: 'Other Income', value: 'Other Income'},

  // Additional 100 sources
  {label: 'YouTube Earnings', value: 'YouTube Earnings'},
  {label: 'Blogging', value: 'Blogging'},
  {label: 'Tutoring', value: 'Tutoring'},
  {label: 'eBook Sales', value: 'eBook Sales'},
  {label: 'Photography', value: 'Photography'},
  {label: 'Art Commissions', value: 'Art Commissions'},
  {label: 'Craft Sales', value: 'Craft Sales'},
  {label: 'Event Hosting', value: 'Event Hosting'},
  {label: 'Stock Trading', value: 'Stock Trading'},
  {label: 'Crypto Trading', value: 'Crypto Trading'},
  {label: 'Course Sales', value: 'Course Sales'},
  {label: 'Podcast Ads', value: 'Podcast Ads'},
  {label: 'Social Media Sponsorship', value: 'Social Media Sponsorship'},
  {label: 'Dropshipping', value: 'Dropshipping'},
  {label: 'Amazon FBA', value: 'Amazon FBA'},
  {label: 'Network Marketing', value: 'Network Marketing'},
  {label: 'Digital Marketing Services', value: 'Digital Marketing Services'},
  {label: 'Web Development', value: 'Web Development'},
  {label: 'App Development', value: 'App Development'},
  {label: 'Graphic Design', value: 'Graphic Design'},
  {label: 'Music Royalties', value: 'Music Royalties'},
  {label: 'DJ Gigs', value: 'DJ Gigs'},
  {label: 'Event Photography', value: 'Event Photography'},
  {label: 'Stock Photography', value: 'Stock Photography'},
  {label: 'Translation Services', value: 'Translation Services'},
  {label: 'Proofreading', value: 'Proofreading'},
  {label: 'Voice Over', value: 'Voice Over'},
  {label: 'Virtual Assistant Work', value: 'Virtual Assistant Work'},
  {label: 'Remote Customer Support', value: 'Remote Customer Support'},
  {label: 'Online Surveys', value: 'Online Surveys'},
  {label: 'Cash Prizes', value: 'Cash Prizes'},
  {label: 'Inheritance', value: 'Inheritance'},
  {label: 'Gift Money', value: 'Gift Money'},
  {label: 'Rent from PG', value: 'Rent from PG'},
  {label: 'Garage Sale', value: 'Garage Sale'},
  {label: 'Old Item Sale', value: 'Old Item Sale'},
  {label: 'Commission Income', value: 'Commission Income'},
  {label: 'Insurance Payout', value: 'Insurance Payout'},
  {label: 'Refunds', value: 'Refunds'},
  {label: 'Festival Bonus', value: 'Festival Bonus'},
  {label: 'Mobile App Ads', value: 'Mobile App Ads'},
  {label: 'Home Tuition', value: 'Home Tuition'},
  {label: 'Daily Wages', value: 'Daily Wages'},
  {label: 'Rent from Shop', value: 'Rent from Shop'},
  {label: 'Freight Income', value: 'Freight Income'},
  {label: 'Commission from Sales', value: 'Commission from Sales'},
  {label: 'Factory Income', value: 'Factory Income'},
  {label: 'Workshop Earnings', value: 'Workshop Earnings'},
  {label: 'Printing Services', value: 'Printing Services'},
  {label: 'Courier Services', value: 'Courier Services'},
  {label: 'Data Entry', value: 'Data Entry'},
  {label: 'Typing Work', value: 'Typing Work'},
  {label: 'Medical Consultation', value: 'Medical Consultation'},
  {label: 'Home Services', value: 'Home Services'},
  {label: 'Repair Services', value: 'Repair Services'},
  {label: 'Electrician Services', value: 'Electrician Services'},
  {label: 'Plumbing Services', value: 'Plumbing Services'},
  {label: 'Carpentry', value: 'Carpentry'},
  {label: 'Makeup Services', value: 'Makeup Services'},
  {label: 'Hairdressing', value: 'Hairdressing'},
  {label: 'Tailoring', value: 'Tailoring'},
  {label: 'Interior Designing', value: 'Interior Designing'},
  {label: 'Architecture Services', value: 'Architecture Services'},
  {label: 'Photography Studio', value: 'Photography Studio'},
  {label: 'Tattoo Art', value: 'Tattoo Art'},
  {label: 'Astrology Services', value: 'Astrology Services'},
  {label: 'Vastu Consultation', value: 'Vastu Consultation'},
  {label: 'Farming Income', value: 'Farming Income'},
  {label: 'Poultry Income', value: 'Poultry Income'},
  {label: 'Fishery Income', value: 'Fishery Income'},
  {label: 'Milk Sales', value: 'Milk Sales'},
  {label: 'Honey Sales', value: 'Honey Sales'},
  {label: 'Organic Farming', value: 'Organic Farming'},
  {label: 'Vending Machine', value: 'Vending Machine'},
  {label: 'Property Flipping', value: 'Property Flipping'},
  {label: 'Interior Contracting', value: 'Interior Contracting'},
  {label: 'Legal Consultation', value: 'Legal Consultation'},
  {label: 'Accounting Services', value: 'Accounting Services'},
  {label: 'CA Services', value: 'CA Services'},
  {label: 'Brokerage', value: 'Brokerage'},
  {label: 'Equity Dividends', value: 'Equity Dividends'},
  {label: 'LIC Commission', value: 'LIC Commission'},
  {label: 'Mutual Fund Payouts', value: 'Mutual Fund Payouts'},
  {label: 'Fixed Deposit Interest', value: 'Fixed Deposit Interest'},
  {label: 'Recurring Deposit Interest', value: 'Recurring Deposit Interest'},
  {label: 'Bank Interest', value: 'Bank Interest'},
  {label: 'Loan EMI Received', value: 'Loan EMI Received'},
  {label: 'Rent from Parking', value: 'Rent from Parking'},
  {label: 'Temple Donations', value: 'Temple Donations'},
  {label: 'NGO Payments', value: 'NGO Payments'},
  {label: 'Rental Equipment', value: 'Rental Equipment'},
  {label: 'Solar Power Income', value: 'Solar Power Income'},
  {label: 'Windmill Income', value: 'Windmill Income'},
  {label: 'Energy Saving Rewards', value: 'Energy Saving Rewards'},
  {label: 'Tuition Fees', value: 'Tuition Fees'},
];
